packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@scarf/scarf': set this to true or false
  '@swc/core': set this to true or false
  cpu-features: set this to true or false
  protobufjs: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: set this to true or false
